*

!package.json
!package-lock.json
!tsconfig.base.json
!apps/api/package.json
!apps/api/tsconfig.json
!apps/api/build.mjs
!apps/api/src/

**/.env
**/.env.*
**/*.env
**/*.pem
**/*.key
**/node_modules
**/dist
**/*.test.ts
**/*.smoke.ts